name: Deploy to Development

concurrency:
  group: development-concurrency
  cancel-in-progress: true

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: equinor/armada/.github/workflows/deploy_to_development.yml@main
    with:
      registry: roboticsdevacr.azurecr.io
      image_name: robotics/sara-utilities
      infrastructure_repository: equinor/analytics-infrastructure
    secrets:
      registry_username: ${{ secrets.ROBOTICS_ROBOTICSDEVACR_USERNAME }}
      registry_password: ${{ secrets.ROBOTICS_ROBOTICSDEVACR_PASSWORD }}
      deploy_key: ${{ secrets.ANALYTICS_INFRASTRUCTURE_DEPLOY_KEY }}
