name: Promote to Production

concurrency:
  group: production-concurrency
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  promote:
    uses: equinor/armada/.github/workflows/promote_to_production.yml@main
    with:
      image_name: robotics/sara-utilities
      staging_registry: roboticsstagingacr.azurecr.io
      production_registry: roboticsprodacr.azurecr.io
      infrastructure_repository: equinor/robotics-infrastructure
      kustomization_base_path: k8s_kustomize/analytics/overlays
      author_name: ${{ github.actor }}
    secrets:
      staging_registry_username: ${{ secrets.ROBOTICS_ROBOTICSSTAGINGACR_USERNAME }}
      staging_registry_password: ${{ secrets.ROBOTICS_ROBOTICSSTAGINGACR_PASSWORD }}
      production_registry_username: ${{ secrets.ROBOTICS_ROBOTICSPRODACR_USERNAME }}
      production_registry_password: ${{ secrets.ROBOTICS_ROBOTICSPRODACR_PASSWORD }}
      deploy_key: ${{ secrets.ANALYTICS_INFRASTRUCTURE_DEPLOY_KEY }}
